// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using farmayopin_backend.Persistencia;

#nullable disable

namespace farmayopin_backend.Migrations
{
    [DbContext(typeof(ManejadorPersistencia))]
    [Migration("20260914120045_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("farmayopin_backend.Modelos.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarritoAsociadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoCompra")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioAsociadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarritoAsociadoId");

                    b.HasIndex("UsuarioAsociadoId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.LineaDeCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LineasDeCarrito");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.LineaDeCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("CompraAsociadaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoAsociadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompraAsociadaId");

                    b.HasIndex("ProductoAsociadoId");

                    b.ToTable("LineasDeCompra");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarritoAsociadoId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarritoAsociadoId")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Compra", b =>
                {
                    b.HasOne("farmayopin_backend.Modelos.Carrito", "CarritoAsociado")
                        .WithMany("ListaDeCompras")
                        .HasForeignKey("CarritoAsociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("farmayopin_backend.Modelos.Usuario", "UsuarioAsociado")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioAsociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarritoAsociado");

                    b.Navigation("UsuarioAsociado");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.LineaDeCarrito", b =>
                {
                    b.HasOne("farmayopin_backend.Modelos.Carrito", "CarritoAsociado")
                        .WithMany("ListaDeLineasCarrito")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("farmayopin_backend.Modelos.Producto", "ProductoAsociado")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarritoAsociado");

                    b.Navigation("ProductoAsociado");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.LineaDeCompra", b =>
                {
                    b.HasOne("farmayopin_backend.Modelos.Compra", "CompraAsociada")
                        .WithMany("ListaDeLineasCompra")
                        .HasForeignKey("CompraAsociadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("farmayopin_backend.Modelos.Producto", "ProductoAsociado")
                        .WithMany()
                        .HasForeignKey("ProductoAsociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraAsociada");

                    b.Navigation("ProductoAsociado");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Usuario", b =>
                {
                    b.HasOne("farmayopin_backend.Modelos.Carrito", "CarritoAsociado")
                        .WithOne("UsuarioAsociado")
                        .HasForeignKey("farmayopin_backend.Modelos.Usuario", "CarritoAsociadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarritoAsociado");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Carrito", b =>
                {
                    b.Navigation("ListaDeCompras");

                    b.Navigation("ListaDeLineasCarrito");

                    b.Navigation("UsuarioAsociado")
                        .IsRequired();
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Compra", b =>
                {
                    b.Navigation("ListaDeLineasCompra");
                });

            modelBuilder.Entity("farmayopin_backend.Modelos.Usuario", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
